In [3]:
def function(a,b,c=None):
    if (c==None):
        return a+b
    else:
        return a+b+c
function(2,3,4)

9

In [4]:
#tuples are immutable
tup=(1,2,'a')
type(tup)


tuple

In [12]:
#lists are mutable
lis=[1,2,3,4]
lis.append(6)
lis

[1, 2, 3, 4, 6]

In [13]:
for i in lis:
    print i


1
2
3
4
6


In [14]:
#iterrating over list
for index in range(len(lis)):
    print lis[index]

1
2
3
4
6


In [15]:
1 in [1,2,3,4]

True

In [28]:
# list Slicing
x='This is string'
print(x[0])

#1st char
print(x[0:1])

#first 3 chars
print(x[0:3])

#last 1 char
print(x[-1])

#last 3rd and 2nd char
print(x[-3:-1])

#first 3 chars
print(x[:3])

T
T
Thi
g
in
Thi


In [29]:
s1='string 1'
s2='string 2'
s1+s2

'string 1string 2'

In [31]:
'string' in s1

True

In [70]:
s3= 'This is simple example of split'
s3.split(' ')[0]

'This'

In [40]:
#Dictionary
dic={'key1':'value1','k2':'value2'}
dic['key3']=None


In [44]:
for keys in dic:
    print(dic[keys])

None
value2
value1


In [45]:
for valuess in dic.values():
    print valuess

None
value2
value1


TypeError: 'dict' object is not callable

In [48]:
import csv
%precision 2

u'%.2f'

In [53]:
list=[1,2,3,4,5,6,7,2,3,5,6]
unique=set(list)
unique
#https://www.coursera.org/learn/python-data-analysis/lecture/hSqE2/python-demonstration-reading-and-writing-csv-files

{1, 2, 3, 4, 5, 6, 7}

In [54]:
#Time
import datetime as dt
import time as tm
tm.time()

1478695471.53

In [60]:
now=dt.datetime.fromtimestamp(tm.time())
now

datetime.datetime(2016, 11, 9, 18, 15, 54, 32040)

In [62]:
print now.year,now.month,now.day,now.hour,now.minute,now.second

2016 11 9 18 15 54


In [66]:
delta=dt.timedelta(days=100)
delta
today=dt.date.today()
today-delta

datetime.date(2016, 8, 1)

In [67]:
#CLasses
class person:
    dept='dept 1'
    def set_name(self,new_name):
        self.name=new_name
    def set_loc(self,new_loc):
        self.loc=new_loc

In [73]:
#functional programming ----chaining oprations ex amp(function,iterable,...)
#Map Fuction
store1=[1,2,7,4,5,6]
store2=[2,3,4,5,6,7]
cheapest = map(min,store1,store2)
cheapest

[1, 2, 4, 4, 5, 6]

In [74]:
store1[0]


1

In [80]:
#Map Function
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']
#goal is to print dergree and lastname   --person is list inside list of people

# For accessing each element of list map() is used
#Important Always remeber while writing map function !!!!!!!!!!!!!!
#syntax of map function is map(method_name,list_to_be_iterated)

def split_title_and_name(person):
    return person.split()[0]+" "+person.split()[2]

map(split_title_and_name, people)


['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vinod', 'Dr. Romero']

In [84]:
#Labda --no name to function---write function in one line
#my_func= lambda aurgument1,aurgument2 : expression
my_func= lambda a1,a2 : a1+a2
my_func(1,2)


#ex2
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

#option 1 syntax of lambda  ---person is another list
for person in people:
    print((lambda x: x.split()[0] + ' ' + x.split()[-1])(person))
    
    
#option 2 lambda inside map
map(lambda person: person.split()[0] + ' ' + person.split()[-1], people)


#https://www.coursera.org/learn/python-data-analysis/lecture/7Pm9b/advanced-python-lambda-and-list-comprehensions

Dr. Brooks
Dr. Collins-Thompson
Dr. Vydiswaran
Dr. Romero


['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [87]:
#List comprehention
lis = [num for num in range(0,100) if num %2 ==0]
lis

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [90]:
import numpy as np

In [94]:
mylist = [1,2,3]
x=np.array(mylist)
x.shape

(3,)

In [96]:
lis2=np.array([[1,2],[3,4]])
lis2.shape

(2, 2)

In [98]:
n=np.arange(0,30,2)

In [100]:
n=n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [101]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [104]:
#Operations
#sum,sub,multi,division,square (x**2),x.dot(y),sum,max,min,mean,std
#Transpose
n.T
#cast 
n=n.astype('f')
n

array([[  0.,   2.,   4.,   6.,   8.],
       [ 10.,  12.,  14.,  16.,  18.],
       [ 20.,  22.,  24.,  26.,  28.]], dtype=float32)

In [105]:
#standered daviation
n.std()

8.6409874

In [107]:
#indexing and slicing
r= np.arange(35)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34,  0]])

In [110]:
#3rd row 4,5,6th colm
r[3,3:6]

array([21, 22, 23])

In [115]:
#1st two row and 1st 5 colm 
r[0:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [116]:
r[r>30]

array([31, 32, 33, 34])

In [117]:
r2=r[:3,:3]
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [118]:
# if array is copied from orignal array, any changes madde in new array will refelect in old
#to create copy that will not reflect changes in oringnal array use arr.copy()
r_new=r.copy()

In [121]:
#iterate over array
arr=np.arange(36)
arr.resize(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [123]:
for row in arr:
    print(row)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[30 31 32 33 34 35]


6

In [124]:
for i in range(len(arr)):
    print arr[i]

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]
[30 31 32 33 34 35]


In [125]:
for i,row in enumerate(arr):
    print('row',i, 'is',row)

('row', 0, 'is', array([0, 1, 2, 3, 4, 5]))
('row', 1, 'is', array([ 6,  7,  8,  9, 10, 11]))
('row', 2, 'is', array([12, 13, 14, 15, 16, 17]))
('row', 3, 'is', array([18, 19, 20, 21, 22, 23]))
('row', 4, 'is', array([24, 25, 26, 27, 28, 29]))
('row', 5, 'is', array([30, 31, 32, 33, 34, 35]))
